// <auto-generated />
using System;
using EmployeeService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeService.AttendanceMigrations
{
    [DbContext(typeof(AttendanceDbContext))]
    [Migration("20260408113439_InitialAttendanceSchema")]
    partial class InitialAttendanceSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeService.Models.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ClockInAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ClockOutAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("EmployeeUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsNonceConsumed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsQrExpired")
                        .HasColumnType("bit");

                    b.Property<string>("PendingQrType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("QrExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("QrNonce")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ScannedInByManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScannedInByManagerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ScannedOutByManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScannedOutByManagerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeUserId", "AttendanceDate")
                        .IsUnique();

                    b.ToTable("AttendanceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
